version: "2"

plugins:
  markdownlint:
    enabled: true

exclude_patterns:
  - ".github/"                                      # Exclude GitHub issue templates
  - "scripts/"                                      # Exclude project build scripts
  - "**/dist/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/__fixtures__/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "**/*.spec.ts"
  - "**/*.integ.ts"
