language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: BovDem50xCSKtL3wphR03IpYOo/V9fQwUj8LHbXcSv2cUxT5gDTXgAe9fLymDZqK71geV6ucQipKRBHazmSb+IENUgSWP9nra3gkdbS058jMQ2DPGuq6y3RlIte040s2YeqriFknGZxOLP6aeZx3PrrN6+xIqEfOXu8laMobB5pL4XxD531yRRdl6i7A6Dm2bvyqdj0mJ7wOt8mA037ptnujXNKCbjPKlFmxiRVYGIzaSF5T/8twkf8zDEEr3fEQ9VEqY3JPco4fp/zaDeFjpxEasudoprXkYeuiHg/xkPqkfXJ6mBuuEjBA1KVtk5i7T3pVw4EGyrxvJvx15nIn/ABqh1/hV7Tg7zCMuQ+aKIlX7cgrNFobIdF/i1/nF00JtiPO1bn+YW6m95FJkVUXRb/lrozn4sYyUhuJmlQ4IRP8CFc4rivzHzASdUw7JOJC9Z+3HsoCwse4XpZOsIA4vRnAxm+kwzLgMuv94ccZiP70pG+7DkbW5IQ6qFlMsUjpqBb7qkkT0ttQolHbYZteKkXCos5CQkqdFZPUXoh5KOwx1apxaOvlFDz/XU5gPEhp9AePoXtDkoJ5nwbfWTgjcyeKA3sJrjhUhMa12VNKYIFq6H7Oh8btqaph3HTwg76MjtNNYpFnrJ7Zda1Rb2ISqp5Us2aFF9O3Kn8bv1CxYtA=

env:
  global:
    - secure: UwhGU5jJxPZ5vVWk6FBSAuwng0lB4Ve46nQwRaE33VPWJGiDTshONsbmzbat1t1rFKnES/rmBpDpTLCp/rTK8S5z0O7RpxblQxxEQJLH431G1pUU1dasERUOqcqi7RTAtfQbEbdzGDOdOBPTC4UvOYjkTOFCMToBB9o3X6U58CGIi/x27Nm5UmC5HjzLsd7u0sMImGthtpy8SIhDCrGWmMpx/ht9jYLV+4DNiQgPVY5sZIEVH7DVHTespF3klsn+tq+XN9CeiIoFL2Jv57oioSX2YnEo8QZqL6ZWnzrYey+y04Xk4BoM5Yq8TST1HvSECClYt2ZzYrSJKP9WQBML8M7n/vyznTBARQ2FPSSHFEQqoUT/xWIDLODEs+rZ0EOgrHxmczgQYWN8D1gZFsR9N/P6v6HaZPdyxGosEtLgstYENDhGy8RbRD9I7YQ3k/JRckyT0g5i59uFWTBdCg3vzclYvM2t5ZrEB8fhhA1n9W+B4FJuduiw0x3FVGV+RN6WPv1enb4ExzXSL2YDTZynX5IjmGWonmHLqXA8Td7incin4NpneesFKDij+cHZb+EJ48BEC3vnMde2ubyA4IuFLMmEz+bHin5m40ABHb8+zqRW75XNlXB9FM+6aEgsxTKG4UNB8gyaumM6Ye/L5HXUviG5sUCgCI+O5/4vycg/qkg=
    - secure: Di8YZjwOmTm3CESQWThEwQYA68tA4N1t2GA33p+0JgKoKla5PUekh9bbclNbfccrlOoqrPLhcn5JdXJJzQ67iw7JfvU9N+xNeSSsOCtdBBFDm7FzOjsIfO6tLGycIFZnaddnc1T7sOooqM+aEqP1eqZ70luLTq2FymSXHDDWK3ivCwGalSmL54KqdqhPdaBBBE4fTG0bJmHMwI4QROc/nO98wmko0RAhoFfvxOJwgGJyAKGv1WEmXzDBeo9gQG6EBIXLZs19yntOkYMVDTw8K6b4/3gSxkGMuETZfFlW9Ji4toqLXCw9xue/ZH1TgWF9wOMvxK+4iIqD35/hiw5UCKxCzz1jVgwWraqmNXpoU81Wi7/iCtvKP3FA73yVdN6gOn/gUGPA/s7N/eKDNOuAZL7pS2hxea93856EZnoTLbqUh0W+Ykf94kQSpL9K74QfqJwoWKMdlSZjTPIG4PGHLdOHdUHCuXEQhfha0ZJVK8cd8Yc0Dx33gCekjAI66cVQaGCpNBd+RoRliaTitARuXhTjQYPBqyZAManqQPYI6d9AOB7atlA6yaddpfATreLSNbtWyTfmrS2wBZdGrvNZm9g4jPJ+22CHxlq5gl5WLsrgnfMdvQjTcDj/gtX6xotCMePe3FyUNYcUG3r4rdgZvCnE215LzC4fu7HcSaQT1AI=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
