language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: BovDem50xCSKtL3wphR03IpYOo/V9fQwUj8LHbXcSv2cUxT5gDTXgAe9fLymDZqK71geV6ucQipKRBHazmSb+IENUgSWP9nra3gkdbS058jMQ2DPGuq6y3RlIte040s2YeqriFknGZxOLP6aeZx3PrrN6+xIqEfOXu8laMobB5pL4XxD531yRRdl6i7A6Dm2bvyqdj0mJ7wOt8mA037ptnujXNKCbjPKlFmxiRVYGIzaSF5T/8twkf8zDEEr3fEQ9VEqY3JPco4fp/zaDeFjpxEasudoprXkYeuiHg/xkPqkfXJ6mBuuEjBA1KVtk5i7T3pVw4EGyrxvJvx15nIn/ABqh1/hV7Tg7zCMuQ+aKIlX7cgrNFobIdF/i1/nF00JtiPO1bn+YW6m95FJkVUXRb/lrozn4sYyUhuJmlQ4IRP8CFc4rivzHzASdUw7JOJC9Z+3HsoCwse4XpZOsIA4vRnAxm+kwzLgMuv94ccZiP70pG+7DkbW5IQ6qFlMsUjpqBb7qkkT0ttQolHbYZteKkXCos5CQkqdFZPUXoh5KOwx1apxaOvlFDz/XU5gPEhp9AePoXtDkoJ5nwbfWTgjcyeKA3sJrjhUhMa12VNKYIFq6H7Oh8btqaph3HTwg76MjtNNYpFnrJ7Zda1Rb2ISqp5Us2aFF9O3Kn8bv1CxYtA=

env:
  global:
    - secure: N8TU38pbkBAwq3EC033DvSFJtFCloPzzwPjAmLkd/bG+9IY1Zw58Vt3r9ZmpMg2AjEnGnQJ8kWChC9c3Bdi1rOkwYbIH92Gd2Fvy0a6s0GHogjO1fOqzZ+jipVSrnSUflhvMtFQDHMrqIFX3kgi0QH2Bfbh5bxw+EpI4pb2Jgf1tB+xZX/jsJHH4X9YgZ09DrrCDLWvjakQwE1mU8RLagm/EkFR1KdG7/cUPaYxpo4QIqm59mULTse3/A5pIOz7WLEbE8AefZvT5A6avuaSmKI5iRLRk/XwxqTckTcibGjlAq5UdrgscbklTLVzoanwKCWZK/5vOfxuJCuYZahbO5h7Ttc7hgnMKxzmbeXJkFsdQF6Qw96gEQefj3YIjm3narbL4SdPf8oW1vj6K8C6L7mjX0DumXus3XmKpa9KwEjnSIXneKauCnGa0In9PbyMp+rjbUQcjOMcMFQcSbsqrH1RVAL4bpSeErBBb4W/Ud7Ta5dW1QdrleLefYffL+gMkYCR1UjN0I9r0gfMl+iJ626+KvcFjD6Cs05d02my2wPMkw0FynuagnHhVbbJw+3Aa80CrhlUH2PgaAklwPSJ2im2h434/oU9DBzW62HYZh9J69xGPVLQxHfwl4vrQk2ZCjtK3mOIh8ke9/t0Gqrj8GgbT3LhVItMQAMrc+Zdcy2o=
    - secure: D7SPfPF79HYf0NoVIgyzCCmsyxvu+dT1CFknfe9r8o4TlRnbn/BpnryjDeOhdkdqG5LvMRx551G6mjcrZHIyVpHCmqTAKa32mDOkT0P+omja4sVQ1M7IQbWhCukA6sprZyFXuEAtg6jrmCzW/LhMfvyYnk1iAtgWmxp7H/Kl0qNS6/mbBOm9c32q1bZ+aU814fwaD0S5MuTmslF/rFWN9F0A+lvez6CUoommow4NU5co6hPG23w+p6EH8Y4lxCmwMPW4jVp0Vf1oUnFLN991krp9POIlhWcOzPRp4nCSS0On+Bksbe1MGrKIYCDUr8x8qkth+aSJxBBMtT7CiM5xtLztO5JZMndo6bg3mQN34Qk3HJU36UvVx9QPx1mg/bwnDjAPQInzgHL1zNdd8Gu1bnDfOG8hCSpJ3ENi2Sw2TZvYumNEhPgpvlHbEM3lHR5WnmoRG/mU1IM7YMd9nw8zbtMLxp8JTl3lMFptBoNXrN05qo5FTGoHGjeSaFB9QLFpgFZ/VT2UyOr0Kdo70N3q27BhQvDLSJw4rdMkAjL4AkuQ4eNNE2iUrkQJ1vFvA4/akV67YswXKR3EB74lEIQ5V5IoMPKNz1KOapwooo5IsVoWmmlJjEj51Cn/zFVb0REPekTn6qjhVGy9R0SLugeuTnLjQNAGFjC8l7en6Y51KPg=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      after_success:
        - yarn global add codecov
        - codecov
